import {Action,ALL_ACTIONS,Floor,Facing,BanditState,Phase,cloneGame,setProgram,beginResolution,step,endRound} from './engine.js';
const PROGRAMS=[];for(const a of ALL_ACTIONS)for(const b of ALL_ACTIONS)for(const c of ALL_ACTIONS)if(a!==b&&a!==c&&b!==c)PROGRAMS.push([a,b,c]);
export function publicGameView(game){const view=structuredClone(game);for(const player of view.players)delete player.programmedActions;return view;}
function visibleScore(view,player,program){const sectionIndex=view.trainSections.findIndex(s=>s.id===player.sectionId),rear=view.trainSections.length-1,rearDanger=sectionIndex===rear?12:sectionIndex===rear-1?5:0;let value=0;program.forEach((action,index)=>{const early=3-index;if(action===Action.HORSE)value+=rearDanger*early+2;if(action===Action.MOVE)value+=(player.facing===Facing.FRONT?5:-rearDanger)*early;if(action===Action.FIRE)value+=6*early;if(action===Action.FLIP)value+=(player.facing===Facing.REAR?4:1)*early;if(action===Action.CHANGE_FLOOR)value+=(player.floor===Floor.INSIDE?3:1)*early;if(action===Action.REFLEX)value+=(player.state===BanditState.STUNNED?10:1)*early});return value;}
function hash(text){let h=2166136261;for(const ch of text){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0;}
function sampledOpponentProgram(view,player,scenario){const ranked=PROGRAMS.map(program=>({program,value:visibleScore(view,player,program)})).sort((a,b)=>b.value-a.value),pool=ranked.slice(0,24);return pool[hash(`${view.roundNumber}:${player.id}:${scenario}`)%pool.length].program;}
function hydrate(view){const game=cloneGame(view);for(const p of game.players)p.programmedActions=[];game.phase=Phase.PROGRAMMING;game.currentActionIndex=0;game.currentTurnOffset=0;game.winnerIds=[];game.unresolved=null;return game;}
function outcomeScore(before,after,playerId){const prior=before.players.find(p=>p.id===playerId),self=after.players.find(p=>p.id===playerId),stateValue={STANDING:900,STUNNED:720,OFF_TRAIN_PENDING:-900,ELIMINATED:-1800}[self.state],section=after.trainSections.findIndex(s=>s.id===self.sectionId),cabooseRisk=section===after.trainSections.length-1?-450:section===after.trainSections.length-2?-100:0,lootGain=(self.lootCards.length-prior.lootCards.length)*320,eliminatedOpponents=after.players.filter(p=>p.id!==playerId&&p.state===BanditState.ELIMINATED).length,stunnedOpponents=after.players.filter(p=>p.id!==playerId&&p.state===BanditState.STUNNED).length,winnerBonus=after.winnerIds?.includes(playerId)?2500:0;return stateValue+cabooseRisk+lootGain+eliminatedOpponents*180+stunnedOpponents*35+winnerBonus+(section>=0?section*18:0);}
function rollout(view,playerId,candidate,scenario){const game=hydrate(view);for(const p of game.players.filter(p=>p.state!==BanditState.ELIMINATED))setProgram(game,p.id,p.id===playerId?candidate:sampledOpponentProgram(view,p,scenario));beginResolution(game);let guard=0;while(game.phase===Phase.RESOLUTION&&guard++<30)step(game);if(game.phase===Phase.ROUND_END)endRound(game);return outcomeScore(view,game,playerId);}
export function chooseAIProgram(publicView,playerId,{scenarios=10}={}){const player=publicView.players.find(p=>p.id===playerId);if(!player)throw new Error(`Unknown AI player ${playerId}`);let best=null;for(const program of PROGRAMS){let value=visibleScore(publicView,player,program)*.2;for(let scenario=0;scenario<scenarios;scenario++)value+=rollout(publicView,playerId,program,scenario)/scenarios;value+=hash(`${player.id}:${program.join(':')}`)/2**32;if(!best||value>best.value)best={program,value}}return [...best.program];}
