import {LOOKS,characterSVG} from './characters.js';
import {Action,ALL_ACTIONS,Floor,Facing,BanditState,Phase,createGame,setProgram,beginResolution,step,endRound,getPlayer,resolutionOrder,resolveLootAmbiguity,findFireTarget} from './engine.js';
import {publicGameView,chooseAIProgram} from './ai.js';
import {APP_VERSION} from './version.js';
import {gunshot,impact,footsteps,climbing,horseRide,carriageBreak,unlockAudio,setSoundEnabled,soundEnabled} from './sound.js';
import {shotEndX,constrainShotDirection} from './presentation.js';
const characters=[{name:'Mei',culture:'East Asian',color:'#f8f7ef',accent:'#98d9ff',artFilter:'none'},{name:'Cole',culture:'White',color:'#111820',accent:'#eef4f1',artFilter:'saturate(.9) brightness(.88)'},{name:'Amara',culture:'Black',color:'#ffd22e',accent:'#39280d',artFilter:'saturate(1.18) brightness(1.06)'},{name:'Mateo',culture:'South American',color:'#8b4dcc',accent:'#f1d7ff',artFilter:'saturate(1.2)'},{name:'Anika',culture:'Indian',color:'#20e868',accent:'#d9ffe4',artFilter:'saturate(1.65) brightness(1.12)'},{name:'Kirra',culture:'Aboriginal Australian',color:'#1885e5',accent:'#d7efff',artFilter:'saturate(1.3) brightness(1.04)'}];let game,selected=[],selectedCharacter=0,busy=false,autoPlay=false;
const lastPositions=new Map();
let speed=1;
const $=s=>document.querySelector(s), label=a=>a.replace('CHANGE_FLOOR','FLOOR').replace('_',' '), symbols={FLIP:'↶',MOVE:'↔',CHANGE_FLOOR:'⇅',FIRE:'✦',REFLEX:'⚡',HORSE:'♞'};
const actionColumns={[Action.FLIP]:0,[Action.MOVE]:1,[Action.CHANGE_FLOOR]:2,[Action.FIRE]:3,[Action.REFLEX]:4,[Action.HORSE]:5};
const atlasStyle=(row,col)=>`--row:${row};--col:${col};--art-filter:${characters[row]?.artFilter||'none'}`;
const actionCard=a=>`<span class="action-symbol">${symbols[a]}</span><span>${label(a)}</span>`;
const setup=$('#setup');
$('#version').textContent=`v${APP_VERSION}`;
let deferredInstall=null;
let offlineReady=false;
const updateNetworkStatus=()=>{$('#offlineStatus').textContent=offlineReady?(navigator.onLine?'ready offline':'offline ready'):(navigator.onLine?'preparing offline…':'offline · cache unverified');$('#offlineStatus').className=offlineReady?'is-offline':'';};
updateNetworkStatus();window.addEventListener('online',updateNetworkStatus);window.addEventListener('offline',updateNetworkStatus);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{offlineReady=true;updateNetworkStatus()}).catch(()=>{$('#offlineStatus').textContent='offline setup unavailable'}));
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstall=event;$('#installButton').hidden=false});
if(matchMedia('(display-mode: standalone)').matches||navigator.standalone)$('#installButton').hidden=true;
$('#installButton').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else $('#installHelp').showModal()};
$('#closeInstall').onclick=()=>$('#installHelp').close();
document.addEventListener('pointerdown',()=>unlockAudio(),{once:true,capture:true});
$('#soundToggle').onclick=async()=>{setSoundEnabled(!soundEnabled());if(soundEnabled())await unlockAudio();$('#soundToggle').textContent=soundEnabled()?'🔊 Sound':'🔇 Muted';};
function buildCharacters(){$('#characterChoices').innerHTML=characters.map((c,i)=>`<button type="button" class="character-choice ${i===selectedCharacter?'selected':''}" data-character="${i}" style="--choice-color:${c.color};--choice-accent:${c.accent}"><span class="atlas-art portrait" style="${atlasStyle(i,1)}"></span><strong>${c.name}</strong><small>${c.culture}</small></button>`).join('');document.querySelectorAll('[data-character]').forEach(b=>b.onclick=()=>{selectedCharacter=Number(b.dataset.character);buildCharacters();buildFacingSetup()});}
function chosenLineup(count){const others=characters.map((_,i)=>i).filter(i=>i!==selectedCharacter);return [selectedCharacter,...others.slice(0,count-1)];}
function buildFacingSetup(){const count=Number($('#aiCount').value)+1,lineup=chosenLineup(count);$('#facingSetup').innerHTML='';lineup.forEach((characterIndex,i)=>$('#facingSetup').insertAdjacentHTML('beforeend',`<label>${i===0?'You · ':`CPU · `}${characters[characterIndex].name}<select data-facing="${i}"><option value="FRONT">Face engine/front ←</option><option value="REAR">Face caboose/rear →</option></select></label>`));}
$('#aiCount').onchange=buildFacingSetup;buildCharacters();buildFacingSetup();setup.showModal();
function drawFirstPlayerId(count){const values=new Uint32Array(1);crypto.getRandomValues(values);return `P${values[0]%count+1}`;}
function showFirstPlayerDraw(){const dialog=$('#draw'),winner=getPlayer(game,game.firstPlayerId),name=$('#drawName'),result=$('#drawResult'),button=$('#enterGame');let tick=0;dialog.showModal();const timer=setInterval(()=>{const candidate=game.players[tick%game.players.length];name.textContent=candidate.name;name.style.color=candidate.color;tick++;if(tick===14){clearInterval(timer);name.textContent=`★ ${winner.name}`;name.style.color=winner.color;result.textContent=`${winner.name} takes the rearmost occupied wagon and acts first.`;button.disabled=false}},85);button.onclick=()=>dialog.close();}
$('#start').onclick=()=>{const count=Number($('#aiCount').value)+1,lineup=chosenLineup(count);const players=lineup.map((characterIndex,i)=>({id:`P${i+1}`,name:i===0?'You':characters[characterIndex].name,color:characters[characterIndex].color,accent:characters[characterIndex].accent,characterIndex,isHuman:i===0,facing:document.querySelector(`[data-facing="${i}"]`).value}));game=createGame({players,lootValues:Array.from({length:count+1},(_,i)=>(i+1)*100),firstPlayerId:drawFirstPlayerId(count)});render();setTimeout(showFirstPlayerDraw,0);};
function human(){return game.players.find(p=>p.isHuman);}
function render(){if(!game)return;document.body.dataset.phase=game.phase;$('#status').textContent=`Round ${game.roundNumber} · ${game.phase.replace('_',' ')}`;renderTrain();renderScores();renderPanel();renderStageHUD();$('#log').innerHTML=game.actionLog.map((entry,index)=>({entry,number:index+1})).reverse().map(({entry,number})=>`<li value="${number}" class="${entry.type.toLowerCase()}">${entry.text}</li>`).join('');}
function trainSkin(s,i){if(i===0)return `<svg class="train-skin engine-skin" viewBox="0 0 180 220" preserveAspectRatio="none" aria-hidden="true"><path d="M9 179h162v18H9z"/><path d="M18 82h105v97H18z"/><path d="M62 52h28v30H62zM68 22h16v32H68z"/><path d="M102 47h58v132h-58z"/><rect x="113" y="67" width="35" height="34" rx="3"/><path d="M10 177 2 151h18z"/><circle cx="45" cy="198" r="17"/><circle cx="131" cy="198" r="17"/><circle cx="45" cy="198" r="6"/><circle cx="131" cy="198" r="6"/></svg>`;return `<svg class="train-skin" viewBox="0 0 180 220" preserveAspectRatio="none" aria-hidden="true"><path d="M7 58 20 39h140l13 19v133H7z"/><path d="M17 74h146v102H17z"/><path d="M24 87h35v45H24zM72 87h35v45H72zM120 87h35v45h-35z"/><path d="M16 151h148M16 164h148"/><circle cx="42" cy="198" r="16"/><circle cx="138" cy="198" r="16"/><circle cx="42" cy="198" r="5"/><circle cx="138" cy="198" r="5"/></svg>`;}
function cowboy(p,position=null){const c=LOOKS[p.characterIndex]||LOOKS[0],meta=characters[p.characterIndex]||characters[0],name=p.isHuman?`You · ${c.name}`:p.name;return `<span title="${name}: ${p.state}, facing ${p.facing}${position!==null?`, position ${position+1} from FRONT`:''}" class="bandit ${p.state.toLowerCase()} facing-${p.facing.toLowerCase()}" data-player="${p.id}" style="--bandit-color:${p.color};--bandit-accent:${p.accent||meta.accent};--skin:${c.skin};--hair:${c.hair}">${characterSVG(p.characterIndex)}<span class="bandit-name">${position!==null?`<b>${position+1}</b> `:''}${name} ${p.facing===Facing.FRONT?'←':'→'}</span></span>`;}
function renderTrain(){const motion=-Math.round(performance.now()),sections=game.trainSections.map((s,i)=>`<article class="section ${i===0?'loco':''} ${i===game.trainSections.length-1?'caboose':''}" data-section="${s.id}" style="--capacity:${Math.max(s.roofOccupants.length,s.insideOccupants.length,2)};--motion-offset:${motion}ms"><span class="car-depth" aria-hidden="true"></span><span class="car-tag">${i===0?'01 · LOCOMOTIVE':`${String(i+1).padStart(2,'0')} · ${i===game.trainSections.length-1?'DETACHES NEXT':s.id}`}</span>${trainSkin(s,i)}<div class="train-wheels" aria-hidden="true"><i></i><i></i></div>${lane(s,Floor.ROOF)}${lane(s,Floor.INSIDE)}</article>`).join('');$('#train').innerHTML=`<div class="landscape" style="--motion-offset:${motion}ms" aria-hidden="true"><i class="sun"></i><i class="mesa far"></i><i class="mesa near"></i><i class="telegraph"></i></div><div class="direction-label"><span>← FRONT</span><span>REAR →</span></div><div class="train" style="--motion-offset:${motion}ms">${sections}</div>`;for(const p of game.players.filter(p=>p.state===BanditState.OFF_TRAIN_PENDING)){const pos=lastPositions.get(p.id)||{x:$('#train').scrollWidth-75,y:260};$('#train').insertAdjacentHTML('beforeend',`<div class="pending-bandit" style="left:${pos.x}px;top:${pos.y}px">${cowboy(p)}<small>RESCUE PENDING</small></div>`);}}
function lane(s,floor){const ids=s[floor===Floor.ROOF?'roofOccupants':'insideOccupants'];return `<div class="lane ${floor.toLowerCase()}" data-lane="${floor}" style="--count:${Math.max(ids.length,1)}"><span class="floor-mark">${floor===Floor.ROOF?'ROOF':'CABIN'} · ← FRONT / REAR →</span>${ids.map((id,i)=>`<div class="position-slot" data-position="${i+1}">${cowboy(getPlayer(game,id),i)}</div>`).join('')}</div>`;}
function renderScores(){$('#scoreboard').innerHTML=`<div class="score-title">PLAYERS · <span class="first-key">★ FIRST</span></div>${game.players.map(p=>{const total=p.lootCards.reduce((sum,c)=>sum+c.value,0),first=p.id===game.firstPlayerId,meta=characters[p.characterIndex]||characters[0];return `<div class="score ${p.state===BanditState.ELIMINATED?'out':''} ${first?'first':''}"><span class="score-dot" style="--swatch:${p.color};--swatch-accent:${p.accent||meta.accent}"></span><strong>${first?'★ ':''}${p.name}</strong><span>${p.lootCards.length} wagon${p.lootCards.length===1?'':'s'} · $${total}</span></div>`}).join('')}`;}
function finishRoundIfNeeded(){if(game.phase===Phase.ROUND_END)endRound(game);}
const reducedMotion=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const narrowScreen=()=>matchMedia('(max-width: 760px)').matches;
// Rules-critical travel must stay readable even when the phone requests reduced motion.
const timing=ms=>(reducedMotion()?Math.max(320,ms*.45):ms)/speed;
const wait=ms=>new Promise(resolve=>setTimeout(resolve,timing(ms)));
function rememberPositions(){const board=$('#train'),br=board.getBoundingClientRect();document.querySelectorAll('[data-player]').forEach(el=>{const r=el.getBoundingClientRect();lastPositions.set(el.dataset.player,{x:r.left-br.left+board.scrollLeft,y:r.top-br.top+board.scrollTop})});}
function renderStageHUD(){$('#autoToggle').disabled=game.phase!==Phase.RESOLUTION;const alive=game.players.filter(p=>p.state!==BanditState.ELIMINATED).length;$('#stageInfo').textContent=`ROUND ${String(game.roundNumber).padStart(2,'0')} / ${alive} RIDERS / ${game.trainSections.length-1} WAGONS`;const p=game.phase===Phase.RESOLUTION?getPlayer(game,resolutionOrder(game)[game.currentTurnOffset]):human();$('#cameraHint').textContent=game.phase===Phase.RESOLUTION?`${p.name} · ${label(p.programmedActions[game.currentActionIndex])} · ${game.currentActionIndex+1}/3`:'Plan three moves. Outlast the train.';}
$('#speed').onchange=e=>{speed=Number(e.target.value)};
$('#focusYou').onclick=()=>{if(game&&!busy)focusOn(document.querySelector(`[data-player="${human().id}"]`));};
function cameraXFor(contentX){const board=$('#train');return Math.max(0,Math.min(board.scrollWidth-board.clientWidth,contentX-board.clientWidth/2));}
function animateCamera(to,duration=narrowScreen()?720:460){const board=$('#train'),from=board.scrollLeft,target=Math.max(0,Math.min(board.scrollWidth-board.clientWidth,to));if(Math.abs(target-from)<2)return Promise.resolve();board.classList.add('camera-following');return new Promise(resolve=>{duration=timing(duration);const started=performance.now();function frame(now){const t=Math.min(1,(now-started)/duration),ease=t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2;board.scrollLeft=from+(target-from)*ease;if(t<1)requestAnimationFrame(frame);else{board.scrollLeft=target;board.classList.remove('camera-following');resolve();}}requestAnimationFrame(frame);});}
function followObject(el,animation){const board=$('#train');let samples=0,visible=0,firstX=null,lastX=null;return new Promise(resolve=>{function frame(){const br=board.getBoundingClientRect(),r=el.getBoundingClientRect(),x=r.left-br.left+board.scrollLeft+r.width/2;board.scrollLeft=cameraXFor(x);const after=el.getBoundingClientRect();samples++;if(after.right>=br.left&&after.left<=br.right)visible++;firstX??=x;lastX=x;if(animation.playState==='finished'||animation.playState==='idle'){board.dataset.lastTracking=JSON.stringify({kind:el.className,samples,visible,firstX,lastX});resolve();return}requestAnimationFrame(frame)}requestAnimationFrame(frame)})}
function focusOn(el,duration=narrowScreen()?720:460){if(!el)return Promise.resolve();const board=$('#train'),br=board.getBoundingClientRect(),r=el.getBoundingClientRect(),x=r.left-br.left+board.scrollLeft+r.width/2;return animateCamera(cameraXFor(x),duration);}
async function shootSequence(p,el,target){el.classList.add('anim-fire');const flash=document.createElement('i');flash.className='muzzle-flash';el.append(flash);gunshot();burst(el,'smoke');await wait(180);const board=$('#train'),br=board.getBoundingClientRect(),sr=el.getBoundingClientRect(),targetEl=target?document.querySelector(`[data-player="${target.id}"]`):null,tr=targetEl?.getBoundingClientRect(),front=p.facing===Facing.FRONT,startX=sr.left-br.left+board.scrollLeft+(front?3:sr.width-3),startY=sr.top-br.top+board.scrollTop+sr.height*.43,targetX=tr?(tr.left-br.left+board.scrollLeft+tr.width/2):null,calculatedEndX=shotEndX(p.facing,{targetX,trainWidth:board.scrollWidth}),endX=constrainShotDirection(p.facing,startX,calculatedEndX),endY=tr?(tr.top-br.top+board.scrollTop+tr.height*.48):startY,bullet=document.createElement('i');bullet.className=`bullet bullet-${p.facing.toLowerCase()}`;bullet.style.left=`${startX}px`;bullet.style.top=`${startY}px`;board.append(bullet);const duration=Math.max(narrowScreen()?950:720,Math.min(narrowScreen()?2100:1750,Math.abs(endX-startX)*(narrowScreen()?3.2:2.7))),animation=bullet.animate([{left:`${startX}px`,top:`${startY}px`},{left:`${endX}px`,top:`${endY}px`}],{duration:timing(duration),easing:'linear',fill:'forwards'}),camera=followObject(bullet,animation);await Promise.all([animation.finished.catch(()=>{}),camera]);bullet.remove();if(targetEl){impact();targetEl.classList.add('impact-flash');burst(targetEl,'hit');await wait(380)}else await wait(280);}
async function horseSequence(p,el){const board=$('#train'),br=board.getBoundingClientRect(),start=el.getBoundingClientRect(),finish=document.querySelector('.section.loco .inside').getBoundingClientRect(),rider=document.createElement('div');rider.className='horse-rider illustrated-rider';rider.style.left=`${start.left-br.left+board.scrollLeft-72}px`;rider.style.top=`${Math.min(board.scrollHeight-180,start.bottom-br.top+board.scrollTop+5)}px`;rider.innerHTML=`<span class="atlas-art mounted-action" style="${atlasStyle(p.characterIndex,actionColumns[Action.HORSE])}"></span>`;board.append(rider);el.style.opacity='0';horseRide();await wait(260);const dx=finish.left-br.left+board.scrollLeft+20-(start.left-br.left+board.scrollLeft),duration=narrowScreen()?3100:2500,animation=rider.animate([{transform:'translate(0,0)'},{transform:`translate(${dx*.18}px,-5px)`,offset:.18},{transform:`translate(${dx*.42}px,3px)`,offset:.42},{transform:`translate(${dx*.7}px,-5px)`,offset:.68},{transform:`translate(${dx*.88}px,2px)`,offset:.84},{transform:`translate(${dx}px,-78px) scale(.7)`,offset:1}],{duration:timing(duration),easing:'ease-in-out',fill:'forwards'}),camera=followObject(rider,animation);await Promise.all([animation.finished.catch(()=>{}),camera]);await wait(260);rider.remove();}
async function animateCurrentAction(){const order=resolutionOrder(game),p=getPlayer(game,order[game.currentTurnOffset]),action=p.programmedActions[game.currentActionIndex],el=document.querySelector(`[data-player="${p.id}"]`);if(!el)return;document.querySelectorAll('#program button').forEach(b=>b.disabled=true);await focusOn(el);await wait(narrowScreen()?480:260);if(p.state===BanditState.OFF_TRAIN_PENDING&&action!==Action.HORSE){el.animate([{opacity:1},{opacity:0}],{duration:timing(650),fill:'forwards'});await wait(650);return;}const fires=action===Action.FIRE&&p.state===BanditState.STANDING||action===Action.REFLEX&&p.state===BanditState.STUNNED;if(p.state===BanditState.STUNNED){el.classList.remove('stunned');el.classList.add('anim-wake');await wait(600);if(![Action.REFLEX,Action.HORSE].includes(action))return;}if(fires){await shootSequence(p,el,findFireTarget(game,p));return}if(action===Action.HORSE){await horseSequence(p,el);return}if(action===Action.MOVE){footsteps();burst(el,'dust');await wait(300);return;}if(action===Action.CHANGE_FLOOR){climbing();await wait(300);return;}const cls={FLIP:'anim-flip',MOVE:`anim-move-${p.facing.toLowerCase()}`,CHANGE_FLOOR:p.floor===Floor.ROOF?'anim-floor-down':'anim-floor',REFLEX:'anim-reflex'}[action];if(cls)el.classList.add(cls);await wait(800);}
function burst(el,type){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const board=$('#train'),b=board.getBoundingClientRect(),r=el.getBoundingClientRect();for(let i=0;i<7;i++){const dot=document.createElement('i');dot.className=`particle ${type}`;dot.style.left=`${r.left-b.left+board.scrollLeft+r.width/2}px`;dot.style.top=`${r.top-b.top+board.scrollTop+(type==='dust'?r.height:r.height*.45)}px`;board.append(dot);const a=dot.animate([{transform:'translate(0,0) scale(.4)',opacity:.9},{transform:`translate(${(i-3)*13}px,${type==='smoke'?-35-i*4:-10-Math.sin(i)*20}px) scale(1.5)`,opacity:0}],{duration:timing(650+i*30),fill:'forwards'});a.finished.finally(()=>dot.remove());}}
async function animateBoardChange(before){const order=resolutionOrder(before),actor=getPlayer(before,order[before.currentTurnOffset]),action=actor.programmedActions[before.currentActionIndex];const animations=[];for(const p of game.players){const old=before.players.find(x=>x.id===p.id),el=document.querySelector(`[data-player="${p.id}"]`),pos=lastPositions.get(p.id);if(!el||!pos||!old||old.sectionId===p.sectionId&&old.floor===p.floor)continue;if(p.id===actor.id&&action===Action.HORSE)continue;const board=$('#train'),b=board.getBoundingClientRect(),r=el.getBoundingClientRect(),dx=pos.x-(r.left-b.left+board.scrollLeft),dy=pos.y-(r.top-b.top+board.scrollTop);el.classList.add(old.floor!==p.floor?'is-climbing':'is-travelling');const a=el.animate([{transform:`translate(${dx}px,${dy}px)`},{transform:`translate(${dx*.5}px,${dy*.5-12}px)`,offset:.5},{transform:'translate(0,0)'}],{duration:timing(narrowScreen()?1450:1100),easing:'ease-in-out'});animations.push(Promise.all([a.finished.catch(()=>{}),p.id===actor.id||p.state===BanditState.STUNNED?followObject(el,a):Promise.resolve()]).then(()=>{el.classList.remove('is-travelling','is-climbing');burst(el,'dust')}));}await Promise.all(animations);}
async function resolveAnimated(){if(busy||game.phase!==Phase.RESOLUTION)return;busy=true;try{rememberPositions();const before=structuredClone(game);await animateCurrentAction();step(game);if(game.phase===Phase.ROUND_END){carriageBreak();document.querySelector('.section.caboose')?.classList.add('anim-detach');await wait(900);finishRoundIfNeeded();}render();document.querySelectorAll('#program button').forEach(b=>b.disabled=true);await animateBoardChange(before);renderPanel();}finally{busy=false;}if(autoPlay&&game.phase===Phase.RESOLUTION){await wait(narrowScreen()?850:600);if(autoPlay)resolveAnimated()}else{autoPlay=false;$('#autoToggle').textContent='▶ Watch round';}}
$('#autoToggle').onclick=()=>{autoPlay=!autoPlay;$('#autoToggle').textContent=autoPlay?'Ⅱ Pause after action':'▶ Watch round';if(autoPlay&&!busy&&game?.phase===Phase.RESOLUTION)resolveAnimated()};
function miniCard(action,index){const p=human();return `<div class="mini-action"><span class="order-badge">${index+1}</span><span class="atlas-art" style="${atlasStyle(p.characterIndex,actionColumns[action])}"></span><strong>${label(action)}</strong></div>`;}
function renderActionPicker(){const p=human();$('#actionCards').innerHTML=ALL_ACTIONS.map(action=>{const order=selected.indexOf(action);return `<button class="action-art-card ${order>=0?'selected':''}" data-pick="${action}"><span class="atlas-art" style="${atlasStyle(p.characterIndex,actionColumns[action])}"></span><span class="card-caption"><b>${symbols[action]} ${label(action)}</b>${order>=0?`<i>${order+1}</i>`:''}</span></button>`}).join('');document.querySelectorAll('[data-pick]').forEach(button=>button.onclick=()=>{const action=button.dataset.pick;if(selected.includes(action))selected=selected.filter(a=>a!==action);else if(selected.length<3)selected.push(action);renderActionPicker()});$('#donePicking').disabled=selected.length!==3;}
function openActionPicker(){renderActionPicker();$('#actionPicker').showModal();}
$('#closePicker').onclick=()=>$('#actionPicker').close();$('#donePicking').onclick=()=>{$('#actionPicker').close();render()};
function renderPanel(){const box=$('#program');
 if(game.phase===Phase.PROGRAMMING){const p=human();box.innerHTML=`<h2>Your secret program</h2><p>Open your hand and choose three illustrated action cards. CPU hands remain hidden.</p><div class="chosen-actions">${selected.length?selected.map(miniCard).join(''):'<span class="empty-hand">No cards selected</span>'}</div><button id="openCards">${selected.length?'Change cards':'Open action cards'}</button><button class="primary" id="lock" ${selected.length!==3?'disabled':''}>Confirm &amp; let CPUs think</button>`;$('#openCards').onclick=openActionPicker;$('#lock').onclick=()=>{const button=$('#lock');button.disabled=true;button.textContent='CPUs are simulating…';setTimeout(()=>{setProgram(game,p.id,selected);const view=publicGameView(game);for(const cpu of game.players.filter(x=>!x.isHuman&&x.state!==BanditState.ELIMINATED))setProgram(game,cpu.id,chooseAIProgram(view,cpu.id));selected=[];beginResolution(game);render()},30)};}
 else if(game.phase===Phase.RESOLUTION){const order=resolutionOrder(game),p=getPlayer(game,order[game.currentTurnOffset]),a=p.programmedActions[game.currentActionIndex];box.innerHTML=`<h2>${p.name} · Action ${game.currentActionIndex+1}</h2><div class="reveal ${p.isHuman?'human':'cpu'}">${actionCard(a)}</div><p>${p.isHuman?'Your programmed action.':'CPU action revealed now.'}</p><div class="resolution-controls"><button class="primary" id="step">Play action</button><button id="all">Resolve round quickly</button></div>`;$('#step').onclick=resolveAnimated;$('#all').onclick=()=>{while(game.phase===Phase.RESOLUTION)step(game);finishRoundIfNeeded();render()};}
 else if(game.phase===Phase.ROUND_END){box.innerHTML='<h2>Round complete</h2><p>Detach the caboose, eliminate occupants, and award Loot.</p><button class="primary" id="end">End round</button>';$('#end').onclick=()=>{endRound(game);render()};}
 else {const defeat=game.outcome==='HUMAN_DEFEAT';box.innerHTML=defeat?`<div class="defeat"><div class="defeat-mark">☠</div><h2>Defeat</h2><p>You were eliminated in Round ${game.roundNumber}.</p></div><button id="again">Try again</button>`:`<h2>Game over</h2><p>Winner${game.winnerIds.length>1?'s':''}: ${game.winnerIds.map(id=>getPlayer(game,id).name).join(', ')}</p><button id="again">New game</button>`;$('#again').onclick=()=>location.reload();}
 if(game.unresolved?.type==='LOOT_TIE_SAME_POSITION'){box.insertAdjacentHTML('beforeend',`<div class="notice">Rule confirmation needed: same-section, same-floor Loot tie. Choose a temporary recipient: ${game.unresolved.playerIds.map(id=>`<button data-loot="${id}">${getPlayer(game,id).name}</button>`).join(' ')}</div>`);box.querySelectorAll('[data-loot]').forEach(b=>b.onclick=()=>{resolveLootAmbiguity(game,b.dataset.loot);render()});}
}

// Explicit local QA entry: deterministic fixtures never appear in the installed game.
if(['localhost','127.0.0.1'].includes(location.hostname)&&new URLSearchParams(location.search).has('qa')){import('../qa/visual-fixtures.js').then(({installFixtures})=>installFixtures(g=>{autoPlay=false;lastPositions.clear();game=g;selected=[];setup.close();render()}));}
