import {Action,ALL_ACTIONS,Floor,Facing,BanditState,Phase,createGame,setProgram,beginResolution,step,endRound,getPlayer,resolutionOrder,resolveLootAmbiguity,findFireTarget} from './engine.js';
import {publicGameView,chooseAIProgram} from './ai.js';
import {APP_VERSION} from './version.js';
import {gunshot,impact,footsteps,climbing,horseRide,carriageBreak,unlockAudio,setSoundEnabled,soundEnabled} from './sound.js';
import {shotEndX,constrainShotDirection} from './presentation.js';
const characters=[{name:'Mei',culture:'East Asian',color:'#2da6a6'},{name:'Cole',culture:'White',color:'#b94d36'},{name:'Amara',culture:'Black',color:'#ddb62e'},{name:'Mateo',culture:'South American',color:'#7650b3'},{name:'Anika',culture:'Indian',color:'#26835c'},{name:'Kirra',culture:'Aboriginal Australian',color:'#2778b8'}];let game,selected=[],selectedCharacter=0;
const $=s=>document.querySelector(s), label=a=>a.replace('CHANGE_FLOOR','FLOOR').replace('_',' '), symbols={FLIP:'↶',MOVE:'↔',CHANGE_FLOOR:'⇅',FIRE:'✦',REFLEX:'⚡',HORSE:'♞'};
const actionColumns={[Action.FLIP]:0,[Action.MOVE]:1,[Action.CHANGE_FLOOR]:2,[Action.FIRE]:3,[Action.REFLEX]:4,[Action.HORSE]:5};
const atlasStyle=(row,col)=>`--row:${row};--col:${col}`;
const actionCard=a=>`<span class="action-symbol">${symbols[a]}</span><span>${label(a)}</span>`;
const setup=$('#setup');
$('#version').textContent=`v${APP_VERSION}`;
let deferredInstall=null;
const updateNetworkStatus=()=>{$('#offlineStatus').textContent=navigator.onLine?'ready offline':'offline';$('#offlineStatus').className=navigator.onLine?'':'is-offline';};
updateNetworkStatus();window.addEventListener('online',updateNetworkStatus);window.addEventListener('offline',updateNetworkStatus);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstall=event;$('#installButton').hidden=false});
if(matchMedia('(display-mode: standalone)').matches||navigator.standalone)$('#installButton').hidden=true;
$('#installButton').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else $('#installHelp').showModal()};
$('#closeInstall').onclick=()=>$('#installHelp').close();
document.addEventListener('pointerdown',()=>unlockAudio(),{once:true,capture:true});
$('#soundToggle').onclick=async()=>{setSoundEnabled(!soundEnabled());if(soundEnabled())await unlockAudio();$('#soundToggle').textContent=soundEnabled()?'🔊 Sound':'🔇 Muted';};
function buildCharacters(){$('#characterChoices').innerHTML=characters.map((c,i)=>`<button type="button" class="character-choice ${i===selectedCharacter?'selected':''}" data-character="${i}"><span class="atlas-art portrait" style="${atlasStyle(i,1)}"></span><strong>${c.name}</strong><small>${c.culture}</small></button>`).join('');document.querySelectorAll('[data-character]').forEach(b=>b.onclick=()=>{selectedCharacter=Number(b.dataset.character);buildCharacters();buildFacingSetup()});}
function chosenLineup(count){const others=characters.map((_,i)=>i).filter(i=>i!==selectedCharacter);return [selectedCharacter,...others.slice(0,count-1)];}
function buildFacingSetup(){const count=Number($('#aiCount').value)+1,lineup=chosenLineup(count);$('#facingSetup').innerHTML='';lineup.forEach((characterIndex,i)=>$('#facingSetup').insertAdjacentHTML('beforeend',`<label>${i===0?'You · ':`CPU · `}${characters[characterIndex].name}<select data-facing="${i}"><option value="FRONT">Face engine/front ←</option><option value="REAR">Face caboose/rear →</option></select></label>`));}
$('#aiCount').onchange=buildFacingSetup;buildCharacters();buildFacingSetup();setup.showModal();
function drawFirstPlayerId(count){const values=new Uint32Array(1);crypto.getRandomValues(values);return `P${values[0]%count+1}`;}
function showFirstPlayerDraw(){const dialog=$('#draw'),winner=getPlayer(game,game.firstPlayerId),name=$('#drawName'),result=$('#drawResult'),button=$('#enterGame');let tick=0;dialog.showModal();const timer=setInterval(()=>{const candidate=game.players[tick%game.players.length];name.textContent=candidate.name;name.style.color=candidate.color;tick++;if(tick===14){clearInterval(timer);name.textContent=`★ ${winner.name}`;name.style.color=winner.color;result.textContent=`${winner.name} takes the rearmost occupied wagon and acts first.`;button.disabled=false}},85);button.onclick=()=>dialog.close();}
$('#start').onclick=()=>{const count=Number($('#aiCount').value)+1,lineup=chosenLineup(count);const players=lineup.map((characterIndex,i)=>({id:`P${i+1}`,name:i===0?'You':characters[characterIndex].name,color:characters[characterIndex].color,characterIndex,isHuman:i===0,facing:document.querySelector(`[data-facing="${i}"]`).value}));game=createGame({players,lootValues:Array.from({length:count+1},(_,i)=>(i+1)*100),firstPlayerId:drawFirstPlayerId(count)});render();setTimeout(showFirstPlayerDraw,0);};
function human(){return game.players.find(p=>p.isHuman);}
function render(){if(!game)return;$('#status').textContent=`Round ${game.roundNumber} · ${game.phase.replace('_',' ')}`;renderTrain();renderScores();renderPanel();$('#log').innerHTML=game.actionLog.map((entry,index)=>({entry,number:index+1})).reverse().map(({entry,number})=>`<li value="${number}" class="${entry.type.toLowerCase()}">${entry.text}</li>`).join('');}
function trainSkin(s,i){if(i===0)return `<svg class="train-skin engine-skin" viewBox="0 0 180 220" aria-hidden="true"><path d="M9 179h162v18H9z"/><path d="M18 82h105v97H18z"/><path d="M62 52h28v30H62zM68 22h16v32H68z"/><path d="M102 47h58v132h-58z"/><rect x="113" y="67" width="35" height="34" rx="3"/><path d="M10 177 2 151h18z"/><circle cx="45" cy="198" r="17"/><circle cx="131" cy="198" r="17"/><circle cx="45" cy="198" r="6"/><circle cx="131" cy="198" r="6"/></svg>`;return `<svg class="train-skin" viewBox="0 0 180 220" aria-hidden="true"><path d="M7 58 20 39h140l13 19v133H7z"/><path d="M17 74h146v102H17z"/><path d="M24 87h35v45H24zM72 87h35v45H72zM120 87h35v45h-35z"/><path d="M16 151h148M16 164h148"/><circle cx="42" cy="198" r="16"/><circle cx="138" cy="198" r="16"/><circle cx="42" cy="198" r="5"/><circle cx="138" cy="198" r="5"/></svg>`;}
function cowboy(p){return `<span title="${p.name}: ${p.state}, facing ${p.facing}" class="bandit ${p.state.toLowerCase()} facing-${p.facing.toLowerCase()}" data-player="${p.id}" style="--bandit-color:${p.color}"><svg class="cowboy" viewBox="0 0 92 92" aria-hidden="true"><path class="shadow" d="M15 82c13-8 48-8 62 0-15 8-47 8-62 0Z"/><g class="figure"><path class="gun" d="M53 42h31v6H53zM78 46h8v5H75z"/><circle cx="46" cy="27" r="12"/><path class="hat" d="M23 18h45v7H23zM34 8h25l7 12H28z"/><path class="coat" d="M31 39h30l9 35H22z"/><path class="limb" d="m30 44-18 20 7 5 19-17zM57 45l13 18-7 5-15-16z"/><path class="boots" d="m29 70-7 14h17l6-14zM51 70l3 14h18L61 70z"/><circle class="badge" cx="46" cy="51" r="9"/><text x="46" y="55">${p.name[0]}</text></g></svg></span>`;}
function renderTrain(){const sections=game.trainSections.map((s,i)=>`<article class="section ${i===0?'loco':''} ${i===game.trainSections.length-1?'caboose':''}" data-section="${s.id}">${trainSkin(s,i)}${lane(s,Floor.ROOF)}${lane(s,Floor.INSIDE)}</article>`).join('');$('#train').innerHTML=`<div class="direction-label"><span>← FRONT</span><span>REAR →</span></div><div class="train">${sections}</div>`;}
function lane(s,floor){const ids=s[floor===Floor.ROOF?'roofOccupants':'insideOccupants'];return `<div class="lane ${floor.toLowerCase()}" data-lane="${floor}">${ids.map(id=>cowboy(getPlayer(game,id))).join('')}</div>`;}
function renderScores(){$('#scoreboard').innerHTML=`<div class="score-title">PLAYERS · <span class="first-key">★ FIRST</span></div>${game.players.map(p=>{const total=p.lootCards.reduce((sum,c)=>sum+c.value,0),first=p.id===game.firstPlayerId;return `<div class="score ${p.state===BanditState.ELIMINATED?'out':''} ${first?'first':''}"><span class="score-dot" style="background:${p.color}"></span><strong>${first?'★ ':''}${p.name}</strong><span>${p.lootCards.length} wagon${p.lootCards.length===1?'':'s'} · $${total}</span></div>`}).join('')}`;}
function finishRoundIfNeeded(){if(game.phase===Phase.ROUND_END)endRound(game);}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function cameraXFor(contentX){const board=$('#train');return Math.max(0,Math.min(board.scrollWidth-board.clientWidth,contentX-board.clientWidth/2));}
function animateCamera(to,duration=420){const board=$('#train'),from=board.scrollLeft,target=Math.max(0,Math.min(board.scrollWidth-board.clientWidth,to));if(Math.abs(target-from)<2)return Promise.resolve();board.classList.add('camera-following');return new Promise(resolve=>{const started=performance.now();function frame(now){const t=Math.min(1,(now-started)/duration),ease=t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2;board.scrollLeft=from+(target-from)*ease;if(t<1)requestAnimationFrame(frame);else{board.classList.remove('camera-following');resolve();}}requestAnimationFrame(frame);});}
function focusOn(el,duration=380){if(!el)return Promise.resolve();const board=$('#train'),br=board.getBoundingClientRect(),r=el.getBoundingClientRect(),x=r.left-br.left+board.scrollLeft+r.width/2;return animateCamera(cameraXFor(x),duration);}
async function shootSequence(p,el,target){await focusOn(el);el.classList.add('anim-fire');const flash=document.createElement('i');flash.className='muzzle-flash';el.append(flash);gunshot();await wait(120);const board=$('#train'),br=board.getBoundingClientRect(),sr=el.getBoundingClientRect(),targetEl=target?document.querySelector(`[data-player="${target.id}"]`):null,tr=targetEl?.getBoundingClientRect(),front=p.facing===Facing.FRONT,startX=sr.left-br.left+board.scrollLeft+(front?3:sr.width-3),startY=sr.top-br.top+board.scrollTop+sr.height*.43,targetX=tr?(tr.left-br.left+board.scrollLeft+tr.width/2):null,calculatedEndX=shotEndX(p.facing,{targetX,trainWidth:board.scrollWidth}),endX=constrainShotDirection(p.facing,startX,calculatedEndX),endY=tr?(tr.top-br.top+board.scrollTop+tr.height*.48):startY,bullet=document.createElement('i');bullet.className=`bullet bullet-${p.facing.toLowerCase()}`;bullet.style.left=`${startX}px`;bullet.style.top=`${startY}px`;board.append(bullet);const duration=Math.max(650,Math.min(1650,Math.abs(endX-startX)*2.5)),animation=bullet.animate([{left:`${startX}px`,top:`${startY}px`},{left:`${endX}px`,top:`${endY}px`}],{duration,easing:'linear',fill:'forwards'}),camera=animateCamera(cameraXFor(endX),duration);await Promise.all([animation.finished.catch(()=>{}),camera]);bullet.remove();if(targetEl){impact();targetEl.classList.add(`anim-hit-${p.facing.toLowerCase()}`);await wait(650)}else await wait(180);}
async function horseSequence(p,el){await focusOn(el);const board=$('#train'),br=board.getBoundingClientRect(),start=el.getBoundingClientRect(),finish=document.querySelector('.section.loco .inside').getBoundingClientRect(),rider=document.createElement('div');rider.className='horse-rider illustrated-rider';rider.style.left=`${start.left-br.left+board.scrollLeft-72}px`;rider.style.top=`${Math.min(board.scrollHeight-180,start.bottom-br.top+board.scrollTop+5)}px`;rider.innerHTML=`<span class="atlas-art mounted-action" style="${atlasStyle(p.characterIndex,actionColumns[Action.HORSE])}"></span>`;board.append(rider);el.style.opacity='0';horseRide();const dx=finish.left-br.left+board.scrollLeft+20-(start.left-br.left+board.scrollLeft),duration=2250,animation=rider.animate([{transform:'translate(0,0)'},{transform:`translate(${dx*.18}px,-5px)`,offset:.18},{transform:`translate(${dx*.42}px,3px)`,offset:.42},{transform:`translate(${dx*.7}px,-5px)`,offset:.68},{transform:`translate(${dx*.88}px,2px)`,offset:.84},{transform:`translate(${dx}px,-78px) scale(.7)`,offset:1}],{duration,easing:'ease-in-out',fill:'forwards'}),camera=animateCamera(cameraXFor(finish.left-br.left+board.scrollLeft+finish.width/2),duration);await Promise.all([animation.finished.catch(()=>{}),camera]);rider.remove();}
async function animateCurrentAction(){const order=resolutionOrder(game),p=getPlayer(game,order[game.currentTurnOffset]),action=p.programmedActions[game.currentActionIndex],el=document.querySelector(`[data-player="${p.id}"]`);if(!el)return;document.querySelectorAll('#program button').forEach(b=>b.disabled=true);await focusOn(el);const fires=action===Action.FIRE&&p.state===BanditState.STANDING||action===Action.REFLEX&&p.state===BanditState.STUNNED;if(fires){await shootSequence(p,el,findFireTarget(game,p));return}if(action===Action.HORSE){await horseSequence(p,el);return}if(action===Action.MOVE)footsteps();if(action===Action.CHANGE_FLOOR)climbing();const cls={FLIP:'anim-flip',MOVE:`anim-move-${p.facing.toLowerCase()}`,CHANGE_FLOOR:'anim-floor',REFLEX:'anim-reflex'}[action];if(cls)el.classList.add(cls);await wait(650);}
async function resolveAnimated(){await animateCurrentAction();step(game);if(game.phase===Phase.ROUND_END){carriageBreak();document.querySelector('.section.caboose')?.classList.add('anim-detach');await wait(900);finishRoundIfNeeded();}render();}
function miniCard(action,index){const p=human();return `<div class="mini-action"><span class="order-badge">${index+1}</span><span class="atlas-art" style="${atlasStyle(p.characterIndex,actionColumns[action])}"></span><strong>${label(action)}</strong></div>`;}
function renderActionPicker(){const p=human();$('#actionCards').innerHTML=ALL_ACTIONS.map(action=>{const order=selected.indexOf(action);return `<button class="action-art-card ${order>=0?'selected':''}" data-pick="${action}"><span class="atlas-art" style="${atlasStyle(p.characterIndex,actionColumns[action])}"></span><span class="card-caption"><b>${symbols[action]} ${label(action)}</b>${order>=0?`<i>${order+1}</i>`:''}</span></button>`}).join('');document.querySelectorAll('[data-pick]').forEach(button=>button.onclick=()=>{const action=button.dataset.pick;if(selected.includes(action))selected=selected.filter(a=>a!==action);else if(selected.length<3)selected.push(action);renderActionPicker()});$('#donePicking').disabled=selected.length!==3;}
function openActionPicker(){renderActionPicker();$('#actionPicker').showModal();}
$('#closePicker').onclick=()=>$('#actionPicker').close();$('#donePicking').onclick=()=>{$('#actionPicker').close();render()};
function renderPanel(){const box=$('#program');
 if(game.phase===Phase.PROGRAMMING){const p=human();box.innerHTML=`<h2>Your secret program</h2><p>Open your hand and choose three illustrated action cards. CPU hands remain hidden.</p><div class="chosen-actions">${selected.length?selected.map(miniCard).join(''):'<span class="empty-hand">No cards selected</span>'}</div><button id="openCards">${selected.length?'Change cards':'Open action cards'}</button><button class="primary" id="lock" ${selected.length!==3?'disabled':''}>Confirm &amp; let CPUs think</button>`;$('#openCards').onclick=openActionPicker;$('#lock').onclick=()=>{const button=$('#lock');button.disabled=true;button.textContent='CPUs are simulating…';setTimeout(()=>{setProgram(game,p.id,selected);const view=publicGameView(game);for(const cpu of game.players.filter(x=>!x.isHuman&&x.state!==BanditState.ELIMINATED))setProgram(game,cpu.id,chooseAIProgram(view,cpu.id));selected=[];beginResolution(game);render()},30)};}
 else if(game.phase===Phase.RESOLUTION){const order=resolutionOrder(game),p=getPlayer(game,order[game.currentTurnOffset]),a=p.programmedActions[game.currentActionIndex];box.innerHTML=`<h2>${p.name} · Action ${game.currentActionIndex+1}</h2><div class="reveal ${p.isHuman?'human':'cpu'}">${actionCard(a)}</div><p>${p.isHuman?'Your programmed action.':'CPU action revealed now.'}</p><div class="resolution-controls"><button class="primary" id="step">Play action</button><button id="all">Resolve round quickly</button></div>`;$('#step').onclick=resolveAnimated;$('#all').onclick=()=>{while(game.phase===Phase.RESOLUTION)step(game);finishRoundIfNeeded();render()};}
 else if(game.phase===Phase.ROUND_END){box.innerHTML='<h2>Round complete</h2><p>Detach the caboose, eliminate occupants, and award Loot.</p><button class="primary" id="end">End round</button>';$('#end').onclick=()=>{endRound(game);render()};}
 else {const defeat=game.outcome==='HUMAN_DEFEAT';box.innerHTML=defeat?`<div class="defeat"><div class="defeat-mark">☠</div><h2>Defeat</h2><p>You were eliminated in Round ${game.roundNumber}.</p></div><button id="again">Try again</button>`:`<h2>Game over</h2><p>Winner${game.winnerIds.length>1?'s':''}: ${game.winnerIds.map(id=>getPlayer(game,id).name).join(', ')}</p><button id="again">New game</button>`;$('#again').onclick=()=>location.reload();}
 if(game.unresolved){box.insertAdjacentHTML('beforeend',`<div class="notice">Rule confirmation needed: same-section, same-floor Loot tie. Choose a temporary recipient: ${game.unresolved.playerIds.map(id=>`<button data-loot="${id}">${getPlayer(game,id).name}</button>`).join(' ')}</div>`);box.querySelectorAll('[data-loot]').forEach(b=>b.onclick=()=>{resolveLootAmbiguity(game,b.dataset.loot);render()});}
}
