let context,enabled=true;
function audio(){if(!enabled)return null;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return null;context??=new AudioContext();return context;}
function prime(ctx){const osc=ctx.createOscillator(),gain=ctx.createGain();gain.gain.setValueAtTime(.0001,ctx.currentTime);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.015);}
export async function unlockAudio(){const ctx=audio();if(!ctx)return false;try{prime(ctx);if(ctx.state==='suspended'||ctx.state==='interrupted')await ctx.resume();if(ctx.state==='running')prime(ctx)}catch{}return ctx.state==='running';}
export function setSoundEnabled(value){enabled=!!value;if(enabled)unlockAudio();}
export function soundEnabled(){return enabled;}
export function soundState(){return !enabled?'muted':context?.state||'locked';}
function tone(frequency,duration,type='sine',volume=.12,delay=0){const ctx=audio();if(!ctx)return;const osc=ctx.createOscillator(),gain=ctx.createGain(),start=ctx.currentTime+delay;osc.type=type;osc.frequency.setValueAtTime(frequency,start);gain.gain.setValueAtTime(volume,start);gain.gain.exponentialRampToValueAtTime(.001,start+duration);osc.connect(gain).connect(ctx.destination);osc.start(start);osc.stop(start+duration);}
function noise(duration=.12,volume=.1,delay=0,cutoff=900){const ctx=audio();if(!ctx)return;const length=Math.floor(ctx.sampleRate*duration),buffer=ctx.createBuffer(1,length,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/length,2);const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain(),start=ctx.currentTime+delay;source.buffer=buffer;filter.type='lowpass';filter.frequency.value=cutoff;gain.gain.value=volume;source.connect(filter).connect(gain).connect(ctx.destination);source.start(start);}
export function gunshot(){const ctx=audio();if(!ctx)return;const length=Math.floor(ctx.sampleRate*.18),buffer=ctx.createBuffer(1,length,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/length,3);const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();filter.type='lowpass';filter.frequency.value=1800;gain.gain.value=.34;source.buffer=buffer;source.connect(filter).connect(gain).connect(ctx.destination);source.start();tone(90,.22,'square',.18);}
export function impact(){tone(75,.18,'sawtooth',.16);tone(45,.25,'square',.08,.03);}
export function footsteps(){[0,.22,.44].forEach((delay,i)=>{tone(i%2?105:82,.075,'triangle',.09,delay);noise(.06,.045,delay,500)});}
export function climbing(){[0,.18,.36,.54].forEach((delay,i)=>{tone(210+i*22,.07,'triangle',.055,delay);noise(.055,.035,delay,1100)});}
export function horseRide(){[0,.25,.5,.75,1,1.25,1.5,1.72].forEach((delay,i)=>{tone(i%2?112:86,.085,'triangle',.14,delay);noise(.07,.07,delay,620)});tone(390,.16,'sawtooth',.055,1.55);tone(520,.2,'triangle',.05,1.68);tone(64,.22,'square',.12,1.92);noise(.18,.13,1.92,700);}
export function carriageBreak(){noise(.22,.25,0,1800);tone(110,.32,'sawtooth',.18);tone(62,.75,'square',.13,.12);[.28,.48,.68,.88].forEach((delay,i)=>{tone(54-i*5,.13,'triangle',.1-i*.015,delay);noise(.1,.055,delay,420)});}
